servicerequest:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_PORT', '5433') | int }}"
      user: "{{ env_var('DBT_USER', 'postgres') }}"
      password: "{{ env_var('DBT_PASS', 'secret') }}"
      dbname: "{{ env_var('DBT_DB', 'source_db') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'analytics') }}"
      threads: 2
